version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html
    depends_on:
      - mysql
      - php
    links:
      - mysql
      - php
  php:
    build: "./php-fpm"
    volumes:
      - ./php-fpm/conf.d/90-mbstring.ini:/usr/local/etc/php/conf.d/90-mbstring.ini
      - ./php-fpm/conf.d/90-timezone.ini:/usr/local/etc/php/conf.d/90-timezone.ini
      - ./html:/var/www/html
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - data-volume:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
volumes:
  data-volume: